import { createHash, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { BuildArtifact, BuilderConfig } from './types.js';
import { getArtifactDirectory, readBuilderState, writeBuilderState } from './persistence.js';

const now = (): string => new Date().toISOString();

export function validateBuilderConfig(input: BuilderConfig): string[] {
  const errors: string[] = [];
  if (!input.name?.trim()) errors.push('name is required');
  if (!input.version?.trim()) errors.push('version is required');
  if (!Array.isArray(input.domainAllowlist) || input.domainAllowlist.length === 0) errors.push('domainAllowlist must contain at least one hostname');
  if (!Array.isArray(input.modules) || input.modules.length === 0) errors.push('modules is required');
  if (input.eip712.enabled) {
    if (!input.eip712.domainName?.trim()) errors.push('eip712.domainName is required');
    if (!input.eip712.domainVersion?.trim()) errors.push('eip712.domainVersion is required');
    if (!Number.isInteger(input.eip712.chainId) || input.eip712.chainId <= 0) errors.push('eip712.chainId must be a positive integer');
    if (!/^0x[a-fA-F0-9]{40}$/.test(input.eip712.verifyingContract)) errors.push('eip712.verifyingContract must be a valid address');
  }
  return errors;
}

function compileScript(config: BuilderConfig, version: string): string {
  const serializedConfig = JSON.stringify(config).replace(/</g, '\\u003c');
  return `/* generated by dashboard builder: ${config.name}@${config.version} */
(() => {
  'use strict';
  const config = ${serializedConfig};
  const allowedDomains = ${JSON.stringify(config.domainAllowlist)};
  if (!allowedDomains.includes(window.location.hostname)) throw new Error('[builder] hostname is not configured for this artifact');
  const listeners = new Set();
  const runtime = {
    version: ${JSON.stringify(version)},
    config,
    getConfig: () => structuredClone(config),
    on(event, listener) { if (event === 'state') listeners.add(listener); return () => listeners.delete(listener); },
    emitState(state) { for (const listener of listeners) listener(state); },
    showTransactionPreview(preview) { runtime.emitState({ type: 'preview', preview }); return preview; },
    showModal(options = {}) { runtime.emitState({ type: 'modal', options }); return { close: () => runtime.emitState({ type: 'modal_closed' }) }; }
  };
  window.DashboardBuilderRuntime = runtime;
})();`;
}

function createManifest(config: BuilderConfig, script: string, createdAt: string, id: string) {
  return {
    schemaVersion: 1,
    id,
    name: config.name,
    version: config.version,
    createdAt,
    checksum: createHash('sha256').update(script).digest('hex'),
    artifact: 'script.js',
    modules: config.modules,
    domainAllowlist: config.domainAllowlist,
    eip712: config.eip712,
  };
}

export async function createBuild(config: BuilderConfig): Promise<BuildArtifact> {
  const errors = validateBuilderConfig(config);
  const id = randomUUID();
  const createdAt = now();
  if (errors.length) {
    const failed: BuildArtifact = { id, status: 'FAILED', config, createdAt, updatedAt: now(), error: errors.join('; ') };
    const state = await readBuilderState();
    await writeBuilderState({ ...state, builds: [...state.builds, failed] });
    return failed;
  }

  const compiling: BuildArtifact = { id, status: 'COMPILING', config, createdAt, updatedAt: now() };
  const state = await readBuilderState();
  await writeBuilderState({ ...state, builds: [...state.builds, compiling] });
  try {
    const script = compileScript(config, id);
    const manifest = createManifest(config, script, createdAt, id);
    const artifactDirectory = getArtifactDirectory(id);
    const scriptPath = join(artifactDirectory, 'script.js');
    const manifestPath = join(artifactDirectory, 'manifest.json');
    await mkdir(artifactDirectory, { recursive: true });
    await writeFile(scriptPath, script, 'utf8');
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
    const ready: BuildArtifact = { ...compiling, status: 'READY', scriptPath, manifestPath, checksum: manifest.checksum, updatedAt: now() };
    const latest = await readBuilderState();
    await writeBuilderState({ ...latest, builds: latest.builds.map((item) => item.id === id ? ready : item) });
    return ready;
  } catch (error) {
    const failed: BuildArtifact = { ...compiling, status: 'FAILED', updatedAt: now(), error: error instanceof Error ? error.message : 'Unknown compile error' };
    const latest = await readBuilderState();
    await writeBuilderState({ ...latest, builds: latest.builds.map((item) => item.id === id ? failed : item) });
    return failed;
  }
}

export async function getBuild(id: string): Promise<BuildArtifact | undefined> {
  const state = await readBuilderState();
  return state.builds.find((build) => build.id === id);
}

export async function listBuilds(): Promise<BuildArtifact[]> {
  const state = await readBuilderState();
  return [...state.builds].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getActiveBuild(): Promise<BuildArtifact | undefined> {
  const state = await readBuilderState();
  return state.activeBuildId ? state.builds.find((build) => build.id === state.activeBuildId) : undefined;
}

export async function publishBuild(id: string): Promise<BuildArtifact | undefined> {
  const state = await readBuilderState();
  const target = state.builds.find((build) => build.id === id);
  if (!target || (target.status !== 'READY' && target.status !== 'PUBLISHED')) return undefined;
  const publishedAt = now();
  const builds = state.builds.map((build) => {
    if (build.id === id) return { ...build, status: 'PUBLISHED' as const, publishedAt, updatedAt: publishedAt };
    return build.status === 'PUBLISHED' ? { ...build, status: 'ROLLED_BACK' as const, updatedAt: publishedAt } : build;
  });
  await writeBuilderState({ builds, activeBuildId: id });
  return builds.find((build) => build.id === id);
}
