import { createHash, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { BuildArtifact, BuilderConfig } from './types.js';

const builds = new Map<string, BuildArtifact>();
const artifactRoot = resolve(process.env.BUILDER_ARTIFACT_ROOT ?? 'artifacts/builds');

const now = (): string => new Date().toISOString();

export function validateBuilderConfig(input: BuilderConfig): string[] {
  const errors: string[] = [];
  if (!input.name?.trim()) errors.push('name is required');
  if (!input.version?.trim()) errors.push('version is required');
  if (!Array.isArray(input.domainAllowlist) || input.domainAllowlist.length === 0) {
    errors.push('domainAllowlist must contain at least one hostname');
  }
  if (!Array.isArray(input.modules) || input.modules.length === 0) errors.push('modules is required');
  if (input.eip712.enabled) {
    if (!input.eip712.domainName?.trim()) errors.push('eip712.domainName is required');
    if (!input.eip712.domainVersion?.trim()) errors.push('eip712.domainVersion is required');
    if (!Number.isInteger(input.eip712.chainId) || input.eip712.chainId <= 0) {
      errors.push('eip712.chainId must be a positive integer');
    }
    if (!/^0x[a-fA-F0-9]{40}$/.test(input.eip712.verifyingContract)) {
      errors.push('eip712.verifyingContract must be a valid address');
    }
  }
  return errors;
}

function compileScript(config: BuilderConfig, manifestVersion: string): string {
  const serializedConfig = JSON.stringify(config).replace(/</g, '\\u003c');
  const domains = JSON.stringify(config.domainAllowlist);
  return `/* generated by dashboard builder: ${config.name}@${config.version} */
(() => {
  'use strict';
  const config = ${serializedConfig};
  const manifestVersion = ${JSON.stringify(manifestVersion)};
  const allowedDomains = ${domains};
  const hostname = window.location.hostname;

  if (!allowedDomains.includes(hostname)) {
    throw new Error('[builder] current hostname is not configured for this artifact');
  }

  const listeners = new Set();
  const runtime = {
    version: manifestVersion,
    config,
    getConfig: () => structuredClone(config),
    on(event, listener) { if (event === 'state') listeners.add(listener); return () => listeners.delete(listener); },
    emitState(state) { for (const listener of listeners) listener(state); },
    showTransactionPreview(preview) {
      runtime.emitState({ type: 'preview', preview });
      return preview;
    },
    showModal(options = {}) {
      runtime.emitState({ type: 'modal', options });
      return { close: () => runtime.emitState({ type: 'modal_closed' }) };
    }
  };

  window.DashboardBuilderRuntime = runtime;
})();`;
}

function createManifest(config: BuilderConfig, script: string, createdAt: string) {
  return {
    schemaVersion: 1,
    name: config.name,
    version: config.version,
    createdAt,
    checksum: createHash('sha256').update(script).digest('hex'),
    artifact: 'script.js',
    modules: config.modules,
    domainAllowlist: config.domainAllowlist,
    eip712: config.eip712,
  };
}

export async function createBuild(config: BuilderConfig): Promise<BuildArtifact> {
  const errors = validateBuilderConfig(config);
  const id = randomUUID();
  const createdAt = now();
  if (errors.length) {
    const failed: BuildArtifact = { id, status: 'FAILED', config, createdAt, updatedAt: now(), error: errors.join('; ') };
    builds.set(id, failed);
    return failed;
  }

  const compiling: BuildArtifact = { id, status: 'COMPILING', config, createdAt, updatedAt: now() };
  builds.set(id, compiling);
  try {
    const script = compileScript(config, id);
    const manifest = createManifest(config, script, createdAt);
    const buildDir = join(artifactRoot, id);
    const scriptPath = join(buildDir, 'script.js');
    const manifestPath = join(buildDir, 'manifest.json');
    await mkdir(dirname(scriptPath), { recursive: true });
    await writeFile(scriptPath, script, 'utf8');
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
    const ready: BuildArtifact = {
      ...compiling,
      status: 'READY',
      scriptPath,
      manifestPath,
      checksum: manifest.checksum,
      updatedAt: now(),
    };
    builds.set(id, ready);
    return ready;
  } catch (error) {
    const failed: BuildArtifact = {
      ...compiling,
      status: 'FAILED',
      updatedAt: now(),
      error: error instanceof Error ? error.message : 'Unknown compile error',
    };
    builds.set(id, failed);
    return failed;
  }
}

export function getBuild(id: string): BuildArtifact | undefined { return builds.get(id); }
export function listBuilds(): BuildArtifact[] {
  return [...builds.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}
